version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - ./backend/server/.env.docker
    volumes:
      - ./backend/sql/01_init.sql:/docker-entrypoint-initdb.d/01_init.sql:ro
      - ./backend/sql/trivia_data.sql:/docker-entrypoint-initdb.d/trivia_data.sql:ro
      - ./backend/sql/02_load_data.sh:/docker-entrypoint-initdb.d/02_load_data.sh:ro
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build:
      context: ./backend/server
    depends_on:
      - db
    env_file:
      - ./backend/server/.env.docker
    environment:
      - FLASK_APP=__init__:app
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - backend

volumes:
  db_data:
    driver: local
